# Generated by Django 5.2.6 on 2025-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('optional_deadline_datetime', models.DateTimeField(blank=True, null=True)),
                ('boolean_field', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='list.tag')),
            ],
        ),
    ]
